version: 0.2

phases:
  install:
    commands:
      - echo Skipping Nginx installation
  build:
    commands:
      - echo Build start
      - mkdir -p output
      - cp index.html output/index.html
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - output/index.html
